src/EduKids/Controllers/ComicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace EduKids.Controllers
{
    public class ComicsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Calvin()
        {
            return View();
        }

        public IActionResult Tintin()
        {
            return View();
        }
    }
}

src/EduKids/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace EduKids.Controllers
{
    public class GamesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }


    }
}

src/EduKids/Controllers/PoemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace EduKids.Controllers
{
    public class PoemsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/EduKids/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace EduKids.Controllers
{
    public class StoriesController : Controller
    {
        // GET: /<controller>/
        public IActionResult booksForYoungChildren()
        {

            return View();
        }

        public IActionResult theGingerbreadMan()
        {
            return View();
        }      

        public IActionResult theGingerbreadManPage2 ()
        {
            return View();
        }

        public IActionResult theGingerbreadManPageFinal()
        {
            return View();
        }
    }
}

src/EduKids/Views/Comics/Calvin.cshtml
<div class="container">
    <div class="row">
        <hr />
    </div>
    <div class="row">
        
        <div class="col-lg-2">
            <h4>Go to:</h4>
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Comics" asp-action="Index">Comics</a></li>
                <li><a asp-controller="YouTubeVideos" asp-action="Index">YouTube Videos</a></li>
                <li><a asp-controller="Rhymes" asp-action="Index">Rhymes</a></li>
                <li><a asp-controller="Games" asp-action="Index">Games</a></li>
                <li><a asp-controller="Poems" asp-action="Index">Poems</a></li>
                <li><a asp-controller="Stories" asp-action="booksForYoungChildren">Stories</a></li>
            </ul>
            <img src="~/images/Comics/Calvin/StupendousMan.jpg" style="height: 170px; width: 150px" />
        </div>
        <div class="col-lg-8" style="background-color:burlywood;">

            <div class="row">
                <h2 style="text-align:left">Calvin & Hobbes <small>Click on the sides of the comic to change strip</small></h2>
                
            </div>
            <div class="row">
                <br />
                <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="15000">
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                        <li data-target="#myCarousel" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="~/images/Comics/Calvin/1.jpg" alt="ASP.NET" class="img-responsive" style="height: 300px; width: 800px" />
                            @*<div class="carousel-caption">
                        <p>
                            Learn how to build ASP.NET apps that can run anywhere.
                            <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                                Learn More
                            </a>
                        </p>
                    </div>*@
                        </div>
                        <div class="item">
                            <img src="~/images/Comics/Calvin/2.png" alt="Visual Studio" class="img-responsive" style="height: 300px; width: 800px" />
                            @*<div class="carousel-caption">
                        <p>
                            There are powerful new features in Visual Studio for building modern web apps.
                            <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                                Learn More
                            </a>
                        </p>
                    </div>*@
                        </div>
                        <div class="item">
                            <img src="~/images/Comics/Calvin/3.jpg" alt="Package Management" class="img-responsive" style="height: 300px; width: 800px" />
                            @*<div class="carousel-caption">
                        <p>
                            Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                            <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                                Learn More
                            </a>
                        </p>
                    </div>*@
                        </div>
                        <div class="item">
                            <img src="~/images/Comics/Calvin/4.jpg" alt="Microsoft Azure" class="img-responsive" style="height: 300px; width: 800px" />
                            @*<div class="carousel-caption">
                        <p>
                            Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                            <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                                Learn More
                            </a>
                        </p>
                    </div>*@
                        </div>
                    </div>
                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" style="color:black" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" style="color:black" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

            </div>
           
            <br />
        
            <div class="row">
                <div class="col-lg-3">
                    @*<a href="#" class="btn btn-warning btn-md">
                    <span class="glyphicon glyphicon-arrow-left"></span> Previous Page
                </a>*@
                </div>
                <div class="col-lg-6">
                    <!--EMPTY-->
                </div>
                <div class="col-lg-3">
                    <a asp-controller="Comics" asp-action="Tintin" class="btn btn-info btn-md">
                        <span class="glyphicon glyphicon-arrow-right"></span> Next Comic - Tintin
                    </a>
                </div>
            </div>
            <br />

        </div>
        <div class="col-lg-2">
            
            <img src="~/images/Comics/Calvin/StupendousMan 2.jpg" style="height: 170px; width: 150px" />
        </div>
    </div>
</div>

src/EduKids/Views/Comics/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!--COMICS INDEX PAGE-->

<hr />

<div class="container">
    <div class="row">

        <!--CATEGORIES SIDEBAR-->
        <div class="col-lg-2">
            <h4>Go to:</h4>
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Comics" asp-action="Index">Comics</a></li>
                <li><a asp-controller="YouTubeVideos" asp-action="Index">YouTube Videos</a></li>
                <li><a asp-controller="Rhymes" asp-action="Index">Rhymes</a></li>
                <li><a asp-controller="Games" asp-action="Index">Games</a></li>
                <li><a asp-controller="Poems" asp-action="Index">Poems</a></li>
                <li><a asp-controller="Stories" asp-action="booksForYoungChildren">Stories</a></li>
            </ul>
        </div>

        <!--MAIN BODY OF THE PAGE-->
        <div class="col-lg-8" style="background-color:darkgray; padding-left:20px;padding-right:20px; border-radius: 10px">

            <div class="row" style="margin-bottom:10px">
                <div class="col-lg-4"></div>
                <div class="col-lg-4" style="background-color:teal; border-radius: 10px;margin-top: 15px; margin-bottom: 10px">
                    <h3 style="text-align:center; color:white">All Comics</</h3>
                </div>
                <div class="col-lg-4"></div>
            </div>
            

            <!--SUBROWS FOR EACH STORY BOOK-->
            
            <div class="row" style="color:white">
                <!--IMAGE-->
                <div class="col-lg-4">
                    <a asp-controller="Comics" asp-action="Calvin">
                        <img src="~/images/Comics/Home Page/Calvin.png" style="height:200px;width:230px; padding-right: 10px; padding-bottom: 10px" />
                        <p style="color:white; text-align:center">Calvin & Hobbes</p> 
                    </a>
                </div>

                <div class="col-lg-4">
                    <img src="~/images/Comics/Home Page/tintin.jpg" style="height:200px; width:230px; padding-right: 10px; padding-bottom: 10px" />
                    <p style="text-align:center">Tintin</p>
                </div>
                
                <div class="col-lg-4">
                    <img src="~/images/Comics/Home Page/DC.jpg" style="height:200px; width:230px; padding-right: 10px; padding-bottom: 10px" />
                    <p style="text-align:center">DC Comics</p>
                </div>
            </div>

            <div class="row" style="color:white">
                <!--IMAGE-->
                <div class="col-lg-4">
                    <img src="~/images/Comics/Home Page/Superman.jpg" style="height:200px;width:230px; padding-right: 10px; padding-bottom: 10px" />
                    <p style="text-align:center">Superman</p>
                </div>

                <div class="col-lg-4">
                    <img src="~/images/Comics/Home Page/Archie.png" style="height:200px; width:230px; padding-right: 10px; padding-bottom: 10px" />
                    <p style="text-align:center">Archie</p>
                </div>

                <div class="col-lg-4">
                    <img src="~/images/Comics/Home Page/Marvel.png" style="height:200px; width:230px; padding-right: 10px; padding-bottom: 10px" />
                    <p style="text-align:center">Marvel</p>
                </div>
            </div>

            <div class="row" style="color:white">
                <!--IMAGE-->
                <div class="col-lg-4">
                    <img src="~/images/Comics/Home Page/Tinkle.png" style="height:230px;width:230px; padding-right: 10px; padding-bottom: 10px" />
                    <p style="text-align:center">Tinkle</p>
                </div>

                <div class="col-lg-4">
                    <img src="~/images/Comics/Home Page/Shikari Shambu.jpg" style="height:230px; width:230px; padding-right: 10px; padding-bottom: 10px" />
                    <p style="text-align:center">Shikari Shambu</p>
                </div>

                <div class="col-lg-4">
                    <img src="~/images/Comics/Home Page/Wolverine.jpg" style="height:230px; width:230px; padding-right: 10px; padding-bottom: 10px" />
                    <p style="text-align:center">Wolverine</p>
                </div>
            </div>

            <!--GO TO PAGE NUMBERS-->

        </div>





        <!--GO TO SIDEBAR-->
        <div class="col-lg-2">
            
        </div>
    </div>





</div>

src/EduKids/Views/Comics/Tintin.cshtml
<div class="container">
    <div class="row">
        <hr />
    </div>
    <div class="row">

        <div class="col-lg-2">
            <h4>Go to:</h4>
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Comics" asp-action="Index">Comics</a></li>
                <li><a asp-controller="YouTubeVideos" asp-action="Index">YouTube Videos</a></li>
                <li><a asp-controller="Rhymes" asp-action="Index">Rhymes</a></li>
                <li><a asp-controller="Games" asp-action="Index">Games</a></li>
                <li><a asp-controller="Poems" asp-action="Index">Poems</a></li>
                <li><a asp-controller="Stories" asp-action="booksForYoungChildren">Stories</a></li>
            </ul>
            <img src="~/images/Comics/Tintin/6.jpg" style="height: 170px; width: 150px" />
        </div>
        <div class="col-lg-8" style="background-color:burlywood;">

            <div class="row">
                <h2 style="text-align:left">Tintin <small>Click on the sides of the comic to change strip</small></h2>

            </div>
            <div class="row">
                <br />
                <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="15000">
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                        <li data-target="#myCarousel" data-slide-to="3"></li>
                        <li data-target="#myCarousel" data-slide-to="4"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="~/images/Comics/Tintin/1.jpg" alt="ASP.NET" class="img-responsive" style="height: 300px; width: 800px" />
                            @*<div class="carousel-caption">
                                    <p>
                                        Learn how to build ASP.NET apps that can run anywhere.
                                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                                            Learn More
                                        </a>
                                    </p>
                                </div>*@
                        </div>
                        <div class="item">
                            <img src="~/images/Comics/Tintin/2.jpg" alt="Visual Studio" class="img-responsive" style="height: 300px; width: 800px" />
                            @*<div class="carousel-caption">
                                    <p>
                                        There are powerful new features in Visual Studio for building modern web apps.
                                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                                            Learn More
                                        </a>
                                    </p>
                                </div>*@
                        </div>
                        <div class="item">
                            <img src="~/images/Comics/Tintin/3.png" alt="Package Management" class="img-responsive" style="height: 300px; width: 800px" />
                            @*<div class="carousel-caption">
                                    <p>
                                        Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                                            Learn More
                                        </a>
                                    </p>
                                </div>*@
                        </div>
                        <div class="item">
                            <img src="~/images/Comics/Tintin/4.jpg" alt="Microsoft Azure" class="img-responsive" style="height: 300px; width: 800px" />
                            @*<div class="carousel-caption">
                                    <p>
                                        Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                                            Learn More
                                        </a>
                                    </p>
                                </div>*@
                        </div>
                        <div class="item">
                            <img src="~/images/Comics/Tintin/5.png" alt="#" class="img-responsive" style="height: 300px; width: 800px" />
                        </div>
                    </div>
                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" style="color:black" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" style="color:black" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

            </div>

            <br />

            <div class="row">
                <div class="col-lg-3">
                    <a asp-controller="Comics" asp-action="Calvin" class="btn btn-info btn-md">
                            <span class="glyphicon glyphicon-arrow-left"></span> Previous Comic - Calvin
                        </a>
                </div>
                <div class="col-lg-6">
                    <!--EMPTY-->
                </div>
                <div class="col-lg-3">
                    @*<a asp-controller="#" asp-action="#" class="btn btn-info btn-md">
                        <span class="glyphicon glyphicon-arrow-right"></span> Next Comic - Tintin
                    </a>*@
                </div>
            </div>
            <br />

        </div>
        <div class="col-lg-2">
            
            <img src="~/images/Comics/Tintin/7.jpg" style="height: 170px; width: 150px" />
        </div>
    </div>
</div>